os:
  - linux

language: php

php:
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env

script:
  - php artisan key:generate
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-text
